version: '3.1'

services:

  db:
    image: mysql:5.7.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: cmpg311
      MYSQL_DATABASE: default_schema
      MYSQL_TCP_PORT: 3306